### ISSUE TITLE
[lab-3] Wstępna wersja algorytmu szeregowania

### ISSUE THREAD

**Issue by nuusk** [nuusk/teoria-szeregowania-zadan#1]
input:
w linii poleceń:
- ./numer_indeksu instancja k h
- np. ./164273 sch10.txt 10 0.4

folder structure:
- ptsz:
  - exe
  - dane (instancje)

output:
- w pierwszej linii wynik
- w drugiej linii sekwencja (np. p3 t0 t1 p4 t2)
- p (pause) oznacza przerwę
- t (task) oznacza zadanie

**Comment by tomaszgil** [comment]
Numeracja k - od 1.
Numeracja zadań - od 0.

Zgadza się?

**Comment by nuusk** [comment]
@tomaszgil Tak
